name: test

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"

jobs:
  test:
    name: test Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #python: ["3.9", "3.10", "3.11", "3.12"]
        python: ["3.9", "3.10"]
        # include:
        #   - os: "macos-latest"
        #     python: "3.10"
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@main
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: test-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'requirements/*') }}
      - run: sudo apt install -y libgdal-dev
      - run: pip install -U pip
      - run: pip install -r requirements/requirements-dev.txt
      - run: pip install ./
      - run: python --version
      - run: python -m pip --version
      - run: pytest --version
      - run: python -m pip cache info
      #- run: mypy searvey
      #- run: make cov
      - run: make test
      # We only run on a single matrix case in order to speed up CI runtime
      #- run: make exec_notebooks
      #  if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == '3.10' }}
